project_id = "vfttlgqsexcdpxihtwzl"

[functions.verify-authenticity]
verify_jwt = false

[functions.certificate-ai]
verify_jwt = false

[functions.nft-metadata]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = false

[functions.verify-public]
verify_jwt = false

[functions.collectai-identify]
verify_jwt = false

[functions.verify-lp-deposit]
verify_jwt = false

[functions.verify-collectai-jwt]
verify_jwt = false

[functions.collectai-callback]
verify_jwt = false

[functions.mint-coa]
verify_jwt = false